"""Added subjects relationship to Teacher model

Revision ID: 3230d096aeb4
Revises: a89dc776a585
Create Date: 2025-05-07 11:54:52.128725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3230d096aeb4'
down_revision = 'a89dc776a585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=7),
               nullable=True,
               existing_server_default=sa.text("'Theory'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=7),
               nullable=False,
               existing_server_default=sa.text("'Theory'"))

    # ### end Alembic commands ###
