"""Add student_group to students

Revision ID: 515f5dc9c7b6
Revises: e718ae2f45a5
Create Date: 2025-05-07 19:13:41.375632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515f5dc9c7b6'
down_revision = 'e718ae2f45a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_group', sa.String(length=50), nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('student_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_group', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('student_group')

    # ### end Alembic commands ###
