"""Added type field to Subject model

Revision ID: a89dc776a585
Revises: 3db18c1012b9
Create Date: 2025-05-07 11:40:49.934279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89dc776a585'
down_revision = '3db18c1012b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('Theory', 'Lab', 'Seminar', name='subject_types'), nullable=False, server_default='Theory'))

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
