"""Add student_group to students

Revision ID: e718ae2f45a5
Revises: 3230d096aeb4
Create Date: 2025-05-07 19:04:01.185385
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e718ae2f45a5'
down_revision = '3230d096aeb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        # Add student_group column
        batch_op.add_column(sa.Column('student_group', sa.String(length=50), nullable=True))
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        # Drop student_group column
        batch_op.drop_column('student_group')

    # ### end Alembic commands ###
